// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Auditorias.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Answers> Answers { get; set; }

    public virtual DbSet<Audits> Audits { get; set; }

    public virtual DbSet<Forms> Forms { get; set; }

    public virtual DbSet<Questions> Questions { get; set; }

    public virtual DbSet<Sections> Sections { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Answers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Answers__3214EC070FAE38AF");

            entity.Property(e => e.IdAudit).HasColumnName("idAudit");
            entity.Property(e => e.IdQuestion).HasColumnName("idQuestion");
            entity.Property(e => e.Score).HasColumnName("score");

            entity.HasOne(d => d.IdAuditNavigation).WithMany(p => p.Answers)
                .HasForeignKey(d => d.IdAudit)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Answers__idAudit__55009F39");

            entity.HasOne(d => d.IdQuestionNavigation).WithMany(p => p.Answers)
                .HasForeignKey(d => d.IdQuestion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Answers__idQuest__55F4C372");
        });

        modelBuilder.Entity<Audits>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Audits__3214EC07FE043190");

            entity.Property(e => e.Area)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("area");
            entity.Property(e => e.AuditType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.IdForm).HasColumnName("idForm");
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("photoUrl");
            entity.Property(e => e.Responsible)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("responsible");

            entity.HasOne(d => d.IdFormNavigation).WithMany(p => p.Audits)
                .HasForeignKey(d => d.IdForm)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Audits__photoUrl__51300E55");
        });

        modelBuilder.Entity<Forms>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Forms__3214EC07A38E8290");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Questions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3214EC0753465AEF");

            entity.Property(e => e.IdSection).HasColumnName("idSection");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("text");

            entity.HasOne(d => d.IdSectionNavigation).WithMany(p => p.Questions)
                .HasForeignKey(d => d.IdSection)
                .HasConstraintName("FK__Questions__idSec__4D5F7D71");
        });

        modelBuilder.Entity<Sections>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sections__3214EC07F11DED5E");

            entity.Property(e => e.IdForm).HasColumnName("idForm");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.IdFormNavigation).WithMany(p => p.Sections)
                .HasForeignKey(d => d.IdForm)
                .HasConstraintName("FK__Sections__idForm__4A8310C6");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}