// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auditorias.Models;

public partial class PeripheralArea
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Audits> Audits { get; set; } = new List<Audits>();
}