// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auditorias.Models;

public partial class Questions
{
    public int Id { get; set; }

    public int? IdSection { get; set; }

    public string Text { get; set; }

    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    public virtual Sections IdSectionNavigation { get; set; }
}