// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auditorias.Models;

public partial class Sections
{
    public int Id { get; set; }

    public int? IdForm { get; set; }

    public string Name { get; set; }

    public virtual Forms IdFormNavigation { get; set; }

    public virtual ICollection<Questions> Questions { get; set; } = new List<Questions>();
}